
CREATE TABLE order_processing.order_details (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    user_id int NOT NULL,
    amount int NOT NULL,
    created_at timestamp NOT NULL,
    modified_at timestamp NOT NULL,
    CONSTRAINT order_details_ak_1 FOREIGN KEY(user_id) REFERENCES user_management.users(id),
    CONSTRAINT order_details_pk PRIMARY KEY  (id)
);

CREATE TABLE order_processing.order_items (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    order_id int NOT NULL,
    product_id int NOT NULL,
    created_at timestamp NOT NULL,
    modified_at timestamp NOT NULL,
    CONSTRAINT order_items_ak_1 FOREIGN KEY(order_id) REFERENCES order_processing.order_details(id),
    CONSTRAINT order_items_ak_2 FOREIGN KEY(product_id) REFERENCES product_management.products(id),
    CONSTRAINT order_items_pk PRIMARY KEY  (id)
);

CREATE TABLE payment_processing.payment_details (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    order_id int NOT NULL,
    amount int NOT NULL,
    status varchar NOT NULL,
    created_at timestamp NOT NULL,
    modified_at timestamp NOT NULL,
    CONSTRAINT payment_details_pk PRIMARY KEY  (id),
    CONSTRAINT payment_details_ak_2 FOREIGN KEY(order_id) REFERENCES order_processing.order_details(id)
);


CREATE TABLE payment_processing.shopping_session (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    user_id int NOT NULL,
    amount int NOT NULL,
    created_at timestamp NOT NULL,
    modified_at timestamp NOT NULL,
    CONSTRAINT shopping_session_pk PRIMARY KEY  (id),
    CONSTRAINT shopping_session_ak_2 FOREIGN KEY(user_id) REFERENCES user_management.users(id)
);

CREATE TABLE payment_processing.cart_item (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    session_id int NOT NULL,
    product_id int NOT NULL,
    quantity int NOT NULL,
    created_at timestamp NOT NULL,
    modified_at timestamp NOT NULL,
    CONSTRAINT cart_item_pk PRIMARY KEY  (id),
    CONSTRAINT cart_item_ak_2 FOREIGN KEY(session_id) REFERENCES payment_processing.shopping_session(id),
    CONSTRAINT cart_item_ak_1 FOREIGN KEY(product_id) REFERENCES product_management.products(id)
);