
CREATE TABLE order_processing.test_tablle (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    test_col varchar NOT NULL

);

insert into order_processing.test_tablle  (id,test_col )
values(1,'2345');