global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    # metrics_path: /prometheus
    static_configs:
      - targets:
          - 'localhost:8002'
          - 'idonotexists:564'   